name: Terraform Plan

on:
  workflow_dispatch:
    inputs:
      terraform-workspace:
        description: 'Terraform workspace'
        required: false
        default: 'dev'
      terraform-stack-to-run-json:
        description: 'Terraform stacks to run'
        required: false
        default: '["rg"]'
      debug-mode:
        description: 'Debug mode'
        required: false
        default: 'false'
env:
  terraform-init-extra-args-json: '["-backend-config=subscription_id=${{ secrets.ARM_BACKEND_SUBSCRIPTION_ID }}", "-backend-config=resource_group_name=${{ secrets.ARM_BACKEND_STORAGE_RG_NAME }}", "-backend-config=storage_account_name=${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT }}", "-backend-config=container_name=${{ secrets.ARM_BACKEND_CONTAINER_NAME }}"]'


permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  packages: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Libre DevOps - Run Terraform for Azure
        uses: libre-devops/terraform-plan@v1
        with:
          terraform-stack-to-run-json: ${{ github.event.inputs.terraform-stack-to-run-json }}
          terraform-workspace: ${{ github.event.inputs.terraform-workspace }}
          debug-mode: ${{ github.event.inputs.debug-mode }}
          terraform-init-extra-args-json: ${{ env.terraform-init-extra-args-json }}
          arm-tenant-id: ${{ secrets.ARM_TENANT_ID }}
          arm-subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          arm-client-id: ${{ secrets.ARM_CLIENT_ID }}
        env:
          TENV_AUTO_INSTALL: true